{{- if .Values.bookinfo.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/managed-by: openshift-gitops
    chaos-mesh.org/inject: enabled
  labels:  
    istio-injection: enabled
{{- end }}