{{- if .Values.bookinfo.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: openshift-gitops
spec:
  project: default
  sources:
    - repoURL: https://github.com/istio/istio.git
      targetRevision: master
      path: samples/bookinfo/platform/kube
      directory:
        include: 'bookinfo.yaml'
    - repoURL: https://github.com/istio/istio.git
      targetRevision: master
      path: samples/bookinfo/networking
      directory:
        include: 'bookinfo-gateway.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo
{{- end }}