---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh2
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: this
    targetRevision: main
    path: servicemesh2
    helm:
      values: |
        namespace: openshift-operators
        operator:
          startingCSV: servicemeshoperator.v2.6.6
          installPlanApproval: Manual
        helper-status-checker:
          approver: true
          checks:
            - operatorName: servicemeshoperator
              namespace:
                name: openshift-operators
              syncwave: '1'
              serviceAccount:
                name: "servicemesh2-status-checker"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
